name: Notificar push a main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: Notificación de GitHub" \
               -H "Priority: high" \
               -d "Se ha subido código a la rama main del repositorio." \
               https://ntfy.sh/devops-itla
